config/routes.rb
Rails.application.routes.draw do
	get 'todos', to: 'todos#index'
	get 'todos/new' #Crear la ruta 'todos/new' con el verbo get
	get 'todos/list'
	post 'todos', to: 'todos#create'
    get 'todos/:id', to: 'todos#show', as: 'todo'
  	get 'todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
	patch 'todos/:id', to: 'todos#update'
  	delete 'todos/:id', to: 'todos#destroy'
  	get 'todos/:id/complete', to: 'todos#complete', as: 'complete_todo'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
	validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	def index
		@todos = Todo.all
	end

	def new
		@todo = Todo.new
	end

	def create
		@todo = Todo.new(todo_params)
		@todo.save
    	redirect_to todos_path
	end

	def show
		@todo = Todo.find(params[:id])
	end

	def edit
    	@todo = Todo.find(params[:id])
 	end

	def update
	    @todo = Todo.find(params[:id])
	    @todo.update(todo_params)
	    redirect_to todos_path
	end

	def destroy
		@todo = Todo.find(params[:id])
		@todo.destroy
		redirect_to todos_path
	end

	def complete
		@todo = Todo.find(params[:id])
		@todo.completed = true
		@todo.save
		redirect_to todos_path
  	end

  	def list
    	@todos = Todo.all
  	end

	private
	def todo_params
		params.require(:todo).permit(:description, :completed)
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Inicio</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to "Crear Tarea", todos_new_path %>
        </li>
        <li><%= link_to "Listar Tareas", todos_list_path %></li>
    
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Todas las Tareas", todos_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">  -->
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/3.3.7/journal/bootstrap.min.css" rel="stylesheet" integrity="sha384-1L94saFXWAvEw88RkpRz8r28eQMvt7kG9ux3DdCqya/P3CfLNtgqzMnyaUa49Pl2" crossorigin="anonymous">
    <link rel="shortcut icon" href="<%= asset_path 'ico/favicon.png'%>">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
   
    <%= yield %>

    <!-- JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true, html: { class: 'form-horizontal' }  do |f| %>
  <fieldset>
    <legend>Creación de Tareas</legend>
      <div class="form-group">
        <div class="col-md-5">
          <%= f.label :description, "Tarea", class: "col-md-2 control-label" %>
        </div>
        <div class="col-md-5">
          <%= f.text_field :description, class: 'form-control'%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-5">
          <%= f. label :completed,"Completada¿?" , class: "col-md-2 control-label"%>
        </div>
        <div class="col-md-5">
          <%= f.check_box :completed, class: 'checkbox'%> 
        </div>
      </div>
 
          
      <div class="form-group">
        <div class="col-md-10 col-lg-offset-2">
          <%= link_to 'Volver', todos_path, class: 'btn btn-default' %>
          <%= f.submit 'Crear ToDo', class: 'btn btn-primary' %>
        </div>
      </div>
  </fieldset>
<% end %>
    

app/views/todos/edit.html.erb
<h1>Editar ToDo</h1>

<%= render 'form' %>

<%= link_to 'Atras', todos_path, class: "btn btn-warning" %>

app/views/todos/index.html.erb
<h1>Tareas Creadas</h1>

<div class="well">

	 <!-- Table -->
	  <table class="table">
	    <thead>
	    <tr>
	      <th>Tarea</th>
	      <th>Estatus</th>
	      <th>Marcar como terminada</th>
	      <th colspan="3">Acciones</th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @todos.each do |todo| %>
	      <tr>
	        <td><%= todo.description %></td>
	        <% if todo.completed == true %>
                <td><span class="glyphicon glyphicon-thumbs-up"> Terminada</td>
            <% else %>
                <td><span class="glyphicon glyphicon-thumbs-down"> Por Hacer</span></td>
            <% end %>
      		<% if todo.completed == true %>
                <td><span class="glyphicon glyphicon-ok"></span> </td>
            <% else %>
                <td><%= link_to 'Terminar', complete_todo_path(todo) , class: 'label label-success'%></td>
            <% end %>

        	<td><%= link_to 'Ver', todo, class: "btn btn-primary" %></td>
            <td><%= link_to 'Eliminar', todo, method: :delete, data: { confirm: 'Respuesta definitiva?' } , class: "btn btn-danger" %></td>
        	<td><%= link_to 'Editar', edit_todo_path(todo), class: "btn btn-info" %></td>
        	
        	

	      </tr>
	    <% end %>
	  </tbody>
	  </table>
</div>

<%= link_to 'List', todos_list_path , class: 'btn btn-primary'%>
        	            
<%= link_to 'Crear ToDo', todos_new_path, class: "btn btn-warning" %>

app/views/todos/list.html.erb
<h1>Todos</h1>


	<div class="row">	
		<div class="col-md-6">
			<% @todos.each do |todo| %>	
				<% if todo.completed == true %>
					<li class="list-group-item list-group-item-success d-flex justify-content-between align-items-center">
					<%= todo.description %>
					<span class="badge badge-primary badge-pill">SI</span>
						</li>
				<% end %>
			<% end %>
		</div>
			
		<div class="col-md-6">
			<% @todos.each do |todo| %>	
				<% if todo.completed == false %>
					<li class="list-group-item list-group-item-danger d-flex justify-content-between align-items-center">
					<%= todo.description %>
					<span class="badge badge-primary badge-pill">NO</span>
						</li>
				<% end %>
			<% end %>
		</div>
	</div>

<br>

<%= link_to 'Volver', todos_path, class: "btn btn-default" %>

app/views/todos/new.html.erb
<h1>Nueva Tarea</h1>
<br>
<%= render 'form' %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ToDo:</strong>
  <%= @todo.description %>
</p>

<p>
  <strong>Completada:</strong>
  <%= @todo.completed %>
</p>


<%= link_to "Edit", edit_todo_path(@todo.id), class: "btn btn-success" %> |
<%= link_to "Atrás", todos_path, class: "btn btn-secondary" %>